---
title: "Introduction to viparc"
author: "Marc Choisy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::knit_hooks$set(margin = function(before, options, envir) {
  if (before) par(mgp = c(1.5, .5, 0), bty = "n", plt = c(.105, .97, .13, .97))
  else NULL
})

knitr::opts_chunk$set(margin = TRUE, prompt = TRUE, comment = "#>",
                      collapse = TRUE, cache = FALSE, autodep = TRUE,
                      dev.args = list(pointsize = 11), fig.height = 3.5,
                      fig.width = 4.24725, fig.retina = 2,
                      fig.align = "center", fig.path = "README-")
```

Heatmap of the surveillance disease and drug usage in several farms for a 
number of weeks:

```{r message = FALSE, eval = FALSE}
library(viparc)
library(dplyr) # for %>%, filter and transmute
data("chcknfarms")
chcknfarms %>%
  filter(CYCLE == 1) %>%
  transmute(space   = FARMCODE,
            time    = WEEK,
            disease = SRespiratory,
            drug    = AntibioticUse) %>%
  heat_map()
```

Note that the input data frame to `heat_map` should have 4 variables named
`space`, `time`, `disease` and `drug`.
